version: "3.8"
services:
  web:
    image: nginx:alpine
    volumes:
      - ./html/react/dist:/usr/share/nginx/html
      - ./config/web/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default

  src:
    image: nginx:alpine
    volumes:
      - ./html/static:/usr/share/nginx/html
      - ./config/src/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default

  apache:
    build: ./config/php
    working_dir: /var/www/html/
    container_name: apache
    ports:
      - "5173:5173"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      default:
        aliases:
          - markedPDF-apache
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    build: ./config/mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mysql-testing:
    build: ./config/mysql
    volumes:
      - ./test_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: ${MYSQL_TEST_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_TEST_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_USER: ${MYSQL_TEST_USER}
      MYSQL_PASSWORD: ${MYSQL_TEST_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    depends_on:
      - mysql

  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - 6379:6379

networks:
  default:
    name: reverse-proxy-network
    external: true